# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='zita',
    version='0.0.1',
    description='Zillion Images To Assess',
    python_requires='>=3.7',
    author='Jesse Yang',
    author_email='hello@yjc.me',
    license='Apache-2.0',
    packages=['zita', 'zita.bin', 'zita.serve', 'zita.train'],
    package_data={'zita.serve': ['*.gql']},
    install_requires=['ariadne>=0.6.0', 'fastai>=1.0.57', 'uvicorn>=0.8.6'],
    extras_require={'dev': ['jupyter>=1.0.0', 'notebook>=6.0.1']},
)
